development:
  adapter: postgresql
  encoding: unicode
  database: my_new_rails_app_development
  pool: 5
  host: localhost
  username: postgres
  password: welcome@2022

test:
  adapter: postgresql
  encoding: unicode
  database: my_new_rails_app_test
  pool: 5
  username: postgres
  password: welcome@2022

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
   database: my_new_rails_app_production